--EMPLOYEE-
SELECT COUNT(EMPID), TYPE
FROM EMP
GROUP BY TYPE

--MANAGER--
SELECT * FROM MNGR
ORDER BY SALARY

--WORKER--
SELECT WRKR.WRKR_EMPID, CUST.NAME, CUST.CUSTOMERID
FROM WRKR
INNER JOIN CUST
ON WRKR.WRKR_EMPID = CUST.WRKR_EMPID

--SUPPLIER--
SELECT SUPP.ITEMTYPE,CLTHNG.ITEMNUM, CLTHNG.DESIGN
FROM SUPP
INNER JOIN CLTHNG
ON SUPP.SUPPLIERID = CLTHNG.SUPP_SUPPLIERID;

--CUSTOMER--
SELECT COUNT(CUSTOMERID), WRKR_EMPID
FROM CUST
GROUP BY WRKR_EMPID

--TRANSACTION--
SELECT * FROM TRNSCT
ORDER BY CUST_CUSTOMERID

--CLTHNG--
SELECT * FROM CLTHNG WHERE PRICE >100
