#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "awort/02081124@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

DROP TABLE EMP CASCADE CONSTRAINTS;
DROP TABLE WRKR CASCADE CONSTRAINTS;
DROP TABLE MNGR CASCADE CONSTRAINTS;
DROP TABLE CUST CASCADE CONSTRAINTS;
DROP TABLE TRNSCT CASCADE CONSTRAINTS;
DROP TABLE SUPP CASCADE CONSTRAINTS;
DROP TABLE CLTHNG CASCADE CONSTRAINTS;
DROP TABLE CLTH_TRANS CASCADE CONSTRAINTS;

exit;
EOF